### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by ElDavoo** [Mikel12455/whafer#1]
Dopo aver installato come da readme:
```
whafer-gui
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Davide\AppData\Roaming\Python\Python311\Scripts\whafer-gui.exe\__main__.py", line 4, in <module>
  File "C:\Users\Davide\AppData\Roaming\Python\Python311\site-packages\whafer\gui.py", line 2, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'
```

**Comment by ElDavoo** [comment]
Funziona reinstallando python su windows includendo tck
