### ISSUE TITLE
Non riesco ad aprire la lista gruppi

### ISSUE THREAD

**Issue by ElDavoo** [Mikel12455/whafer#2]
Quando lo faccio succede questo:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Davide\AppData\Roaming\Python\Python311\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\Davide\AppData\Roaming\Python\Python311\site-packages\whafer\gui.py", line 449, in mostra_vista_gruppi
    self.vista = GruppiView(self, self.progetto.sorgente.gruppi)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Davide\AppData\Roaming\Python\Python311\site-packages\whafer\db.py", line 43, in gruppi
    timestamp = [datetime.fromtimestamp(ts/1000) if ts is not None else None for ts in timestamp]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Davide\AppData\Roaming\Python\Python311\site-packages\whafer\db.py", line 43, in <listcomp>
    timestamp = [datetime.fromtimestamp(ts/1000) if ts is not None else None for ts in timestamp]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
```

**Comment by Mikel12455** [comment]
Questo programma l'ho dovuto finire molto velocemente, pertanto è pieno di problemi ed ha bisogno di una riscrittura completa 😅.

Grazie comunque per aver aperto la issue: la manterrò aperta per tornarci in un secondo momento.
